name: codex-review

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
    paths:
      - "src/**"
      - "app/**"
      - "*.py"
      - "*.js"
      - "*.ts"
      - "*.jsx"
      - "*.tsx"
      - "*.json"
      - "!README.md"
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    name: Codex PR review
    runs-on: ubuntu-latest
    timeout-minutes: 12
    environment: ci-codex
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Codex CLI
        run: npm i -g @openai/codex

      - name: Run Codex review (comments)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          codex --version || true
          echo "🧩 Invoking Codex review with GitHub comment output"
          codex review --format github || echo "codex review completed (non-blocking)"
